# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3862090451cefaa6d00541777c15ba35"
name = "first-app"
handle = "first-app-1477"
application_url = "https://bags-normal-useful-nest.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bags-normal-useful-nest.trycloudflare.com/auth/callback",
  "https://bags-normal-useful-nest.trycloudflare.com/auth/shopify/callback",
  "https://bags-normal-useful-nest.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
